In [5]:
pip install qgrid

In [6]:
#imports
import math
import scipy as sc
import numpy.matlib
import numpy as np
import operator
import pandas as pd
import qgrid
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from numpy import random
from sklearn.model_selection import StratifiedKFold
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.preprocessing import scale
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
import time
from sklearn.feature_selection import RFE



In [7]:
from sklearn import datasets
db = np.loadtxt('./letter-recognition.data',delimiter=',',skiprows=0,dtype=bytes).astype(str)
X = db[0::, 1::] # extracting
Y = db[0::,0]
j=0;
for i in Y:
    Y[j]=ord(i) #chr(i)
    j+=1
data=X.astype(float)
Y=Y.astype(float)
X=X.astype(float)
print(Y)
print(X)

[84. 73. 68. ... 84. 83. 65.]
[[ 2.  8.  3. ...  8.  0.  8.]
 [ 5. 12.  3. ...  8.  4. 10.]
 [ 4. 11.  6. ...  7.  3.  9.]
 ...
 [ 6.  9.  6. ... 12.  2.  4.]
 [ 2.  3.  4. ...  9.  5.  8.]
 [ 4.  9.  6. ...  7.  2.  8.]]


In [8]:
from sklearn.naive_bayes import MultinomialNB
#Naive Bayes
#Validamos el modelo
Folds = 4
random.seed(19680801)
ETrain = np.zeros(Folds)
EVal = np.zeros(Folds)
Eficiencia=np.zeros(Folds)
Precision=np.zeros(Folds)
Sensibilidad=np.zeros(Folds)
Fscore=np.zeros(Folds)
skf = StratifiedKFold(n_splits=Folds)
j = 0
model = MultinomialNB()

for train, test in skf.split(X, Y):
    Xtrain = X[train,:]
    Ytrain = Y[train]
    Xtest = X[test,:]
    Ytest = Y[test]
    print(Ytest)
    #Normalizamos los datos
    media = np.mean(Xtrain)
    desvia = np.std(Xtrain)
    #Haga el llamado a la función para crear y entrenar el modelo usando los datos de entrenamiento
    model.fit(Xtrain,Ytrain)  
    #Validación
    Ytrain_pred = model.predict(Xtrain)
    Yest = model.predict(Xtest)
    print(Yest)
    print(Yest.shape)
    #Evaluamos las predicciones del modelo con los datos de test
    
    Eficiencia[j] = accuracy_score(Ytest, Yest)
    Precision[j] =np.mean(precision_score(Ytest, Yest, average=None))
    Sensibilidad[j]=np.mean(recall_score(Ytest, Yest, average=None))
    Fscore[j]=np.mean(f1_score(Ytest, Yest, average=None))
    
    ETrain[j] = np.mean(Ytrain_pred.ravel() == Ytrain.ravel())
    EVal[j] = np.mean(Yest.ravel() == Ytest.ravel())    
    j += 1
print('Eficiencia= '+str(Eficiencia)) 
print('Precisiòn= '+str(Precision)) 
print('Sensibilidad='+str(Sensibilidad)) 
print('Fscore= '+str(Fscore)) 
print('Eficiencia durante el entrenamiento = ' + str(np.mean(ETrain)) + '+-' + str(np.std(ETrain)))
print('Eficiencia durante la validación = ' + str(np.mean(EVal)) + '+-' + str(np.std(EVal)))

[84. 73. 68. ... 87. 87. 87.]
[73. 65. 65. ... 87. 87. 87.]
(5000,)
[74. 74. 72. ... 87. 87. 87.]
[74. 74. 88. ... 77. 87. 87.]
(5000,)
[72. 84. 72. ... 81. 82. 81.]
[75. 66. 72. ... 81. 67. 81.]
(5000,)
[66. 66. 86. ... 84. 83. 65.]
[66. 66. 80. ... 84. 90. 65.]
(5000,)
Eficiencia= [0.5566 0.554  0.5578 0.545 ]
Precisiòn= [0.56493613 0.55649172 0.56124294 0.54879155]
Sensibilidad=[0.55522429 0.55251394 0.55593474 0.54365455]
Fscore= [0.54482405 0.54191875 0.54597781 0.53180846]
Eficiencia durante el entrenamiento = 0.5536833333333333+-0.0020866640042581474
Eficiencia durante la validación = 0.55335+-0.005012733785071748


In [9]:
#Gradient boosting tree
def entrenamientoRF(arboles , variablesPorNodo, modelo):
    from sklearn.ensemble import RandomForestClassifier as RF
    from sklearn.ensemble import BaggingClassifier as BC

    #Validamos el modelo
    Folds = 4
    random.seed(19680801)
    ETrain = np.zeros(Folds)
    EVal = np.zeros(Folds)
    Eficiencia=np.zeros(Folds)
    Precision=np.zeros(Folds)
    Sensibilidad=np.zeros(Folds)
    Fscore=np.zeros(Folds)
    skf = StratifiedKFold(n_splits=Folds)
    j = 0
    for train, test in skf.split(X, Y):
        Xtrain = X[train,:]
        Ytrain = Y[train]
        Xtest = X[test,:]
        Ytest = Y[test]

        #Normalizamos los datos
        media = np.mean(Xtrain)
        desvia = np.std(Xtrain)
        #Haga el llamado a la función para crear y entrenar el modelo usando los datos de entrenamiento
        if modelo==0:
            #Haga el llamado a la función para crear y entrenar el modelo usando los datos de entrenamiento
            model = RF(n_estimators=arboles,max_features=variablesPorNodo)  
            model.fit(Xtrain,Ytrain)
            #Validación
            Ytrain_pred = model.predict(Xtrain)
            Yest = model.predict(Xtest) 
        if modelo==1:
            model = BC(n_estimators=arboles,max_features=variablesPorNodo*16 )
            model.fit(Xtrain,Ytrain)
            #Validación
            Ytrain_pred = model.predict(Xtrain)
            Yest = model.predict(Xtest) 
        
        Eficiencia[j] = accuracy_score(Ytest, Yest)
        Precision[j] =np.mean(precision_score(Ytest, Yest, average=None))
        Sensibilidad[j]=np.mean(recall_score(Ytest, Yest, average=None))
        Fscore[j]=np.mean(f1_score(Ytest, Yest, average=None))
    
        #Evaluamos las predicciones del modelo con los datos de test
        ETrain[j] = np.mean(Ytrain_pred.ravel() == Ytrain.ravel())
        EVal[j] = np.mean(Yest.ravel() == Ytest.ravel())
        j += 1

    
    eficiencia = np.mean(EVal)
    intervaloConfianza = np.std(EVal)
    return eficiencia, intervaloConfianza, np.mean(Eficiencia),np.mean(Precision), np.mean(Sensibilidad), np.mean(Fscore)

In [ ]:
#Calculando Numero de arboles por Variables analizadas por nodo
randn = np.random.randn
df_types2 = pd.DataFrame({
    'Numero de arboles' : pd.Series([5,5,5,5,5,5,10,10,10,10,10,10,20,20,20,20,20,20,50,50,50,50,50,50,100,100,100,100,100,100]), 'Variables analizadas por nodo' : pd.Series([3,6,9,12,15,16,3,6,9,12,15,16,3,6,9,12,15,16,3,6,9,12,15,16,3,6,9,12,15,16])})
df_types2["Eficiencia en validacion"] = ""
df_types2["Intervalo de confianza"] = ""
df_types2["Eficiencia"] = ""
df_types2["Precisiòn"] = ""
df_types2["Sensibilidad"] = ""
df_types2["Fscore"] = ""
#df_types.sort_index(inplace=True)
df_types2.set_index(['Numero de arboles','Variables analizadas por nodo'], inplace=True)

arrEficienciaVal = []
arrInConfianza= []
arrEficiencia=[]
arrPrecision=[]
arrSensibilidad=[]
arrFscore=[]
for item in df_types2.index:
    eficienciaVal, intervaloConfianza,Eficiencia, Precision, Sensibilidad, Fscore= entrenamientoRF(int(item[0]),int(item[1]),0)
    arrEficienciaVal.append(eficienciaVal)
    arrInConfianza.append(intervaloConfianza)
    arrEficiencia.append(Eficiencia)
    arrPrecision.append(Precision)
    arrSensibilidad.append(Sensibilidad)
    arrFscore.append(Fscore)
    
df_types2["Eficiencia en validacion"] = arrEficienciaVal
df_types2["Intervalo de confianza"] = arrInConfianza
df_types2["Eficiencia"] = arrEficiencia
df_types2["Precisiòn"] = arrPrecision
df_types2["Sensibilidad"] = arrSensibilidad
df_types2["Fscore"] = arrFscore

In [ ]:
qgrid_widget = qgrid.show_grid(df_types2, show_toolbar=False)
qgrid_widget
qgrid_widget.get_changed_df()

In [ ]:
#Redes Neuronales Artificiales
def entrenamientoRNA(nroCapasOcultas, neuronasPorCapa):
    from sklearn.neural_network import MLPClassifier
    from sklearn.model_selection import StratifiedKFold

    Folds = 4
    random.seed(19680801)
    ETrain = np.zeros(Folds)
    EVal = np.zeros(Folds)
    Eficiencia=np.zeros(Folds)
    Precision=np.zeros(Folds)
    Sensibilidad=np.zeros(Folds)
    Fscore=np.zeros(Folds)
    skf = StratifiedKFold(n_splits=Folds)
    j = 0
    for train, test in skf.split(X, Y):
        Xtrain = X[train,:]
        Ytrain = Y[train]
        Xtest = X[test,:]
        Ytest = Y[test]

        #Normalizamos los datos
        media = np.mean(Xtrain)
        desvia = np.std(Xtrain)
        #Haga el llamado a la función para crear y entrenar el modelo usando los datos de entrenamiento

        if(nroCapasOcultas==1):
            mlp=MLPClassifier(activation='tanh',max_iter = 700,hidden_layer_sizes=(neuronasPorCapa))
        else:
            mlp=MLPClassifier(activation='tanh',max_iter = 700,hidden_layer_sizes=(neuronasPorCapa,neuronasPorCapa))
        
        mlp.fit(Xtrain,Ytrain)
        
        Ytrain_pred = mlp.predict(Xtrain)
        Yest = mlp.predict(Xtest)          
        
        Eficiencia[j] = accuracy_score(Ytest, Yest)
        Precision[j] =np.mean(precision_score(Ytest, Yest, average=None))
        Sensibilidad[j]=np.mean(recall_score(Ytest, Yest, average=None))
        Fscore[j]=np.mean(f1_score(Ytest, Yest, average=None))
    
        #Evaluamos las predicciones del modelo con los datos de test
        EVal[j] = np.mean(Yest.ravel() == Ytest.ravel())
        j += 1

    
    eficiencia = np.mean(EVal)
    intervaloConfianza = np.std(EVal)
    return eficiencia, intervaloConfianza, np.mean(Eficiencia),np.mean(Precision), np.mean(Sensibilidad), np.mean(Fscore)

In [ ]:
#Aplicando Redes Neuronales Artificiales 
df_types2 = pd.DataFrame({
    'N. de capas ocultas' : pd.Series([1,1,1,1,1,2,2,2,2,2]),
    'Neuronas por capa' : pd.Series([20,24,28,32,36,20,24,28,32,36])})
df_types2["Eficiencia en validacion"] = ""
df_types2["Intervalo de confianza"] = ""
df_types2["Eficiencia"] = ""
df_types2["Precisiòn"] = ""
df_types2["Sensibilidad"] = ""
df_types2["Fscore"] = ""

df_types2.set_index(['N. de capas ocultas','Neuronas por capa'], inplace=True)

arrEficienciaVal = []
arrInConfianza= []
arrEficiencia=[]
arrPrecision=[]
arrSensibilidad=[]
arrFscore=[]

for h in df_types2.index:
    eficienciaVal, intervaloConfianza,Eficiencia, Precision, Sensibilidad, Fscore = entrenamientoRNA(int(h[0]),int(h[1]))   
    arrEficienciaVal.append(eficienciaVal)
    arrInConfianza.append(intervaloConfianza)
    arrEficiencia.append(Eficiencia)
    arrPrecision.append(Precision)
    arrSensibilidad.append(Sensibilidad)
    arrFscore.append(Fscore)
        
df_types2["Eficiencia en validacion"] = arrEficienciaVal
df_types2["Intervalo de confianza"] = arrInConfianza
df_types2["Eficiencia"] = arrEficiencia
df_types2["Precisiòn"] = arrPrecision
df_types2["Sensibilidad"] = arrSensibilidad
df_types2["Fscore"] = arrFscore

In [ ]:
qgrid_widget = qgrid.show_grid(df_types2, show_toolbar=False)
qgrid_widget
qgrid_widget.get_changed_df()

In [ ]:
#Maquina de vectores
from sklearn import preprocessing
from sklearn.svm import SVC
def entrenamientoMV(kernel, c, gamma):

    Folds = 4
    random.seed(19680801)
    ETrain = np.zeros(Folds)
    EVal = np.zeros(Folds)
    Eficiencia=np.zeros(Folds)
    Precision=np.zeros(Folds)
    Sensibilidad=np.zeros(Folds)
    Fscore=np.zeros(Folds)
    Porcentaje=np.zeros(Folds)
    skf = StratifiedKFold(n_splits=Folds)
    j = 0
    for train, test in skf.split(X, Y):   
        Xtrain = X[train,:]
        Ytrain = Y[train]
        Xtest = X[test,:]
        Ytest = Y[test]

        #Normalizamos los datos
        media = np.mean(Xtrain)
        desvia = np.std(Xtrain)

        #Haga el llamado a la función para crear y entrenar el modelo usando los datos de entrenamiento        
        if( kernel == 'linear'):
            modelo = SVC(kernel= kernel, C=c, decision_function_shape='ovo')
        else:
            modelo = SVC(kernel= kernel, C=c, gamma=gamma, decision_function_shape='ovo') 
      
        modelo.fit(Xtrain,Ytrain)
        
        Ytrain_pred = modelo.predict(Xtrain)       
        Yest = modelo.predict(Xtest)          
        
        Eficiencia[j] = accuracy_score(Ytest, Yest)
        Precision[j] =np.mean(precision_score(Ytest, Yest, average=None))
        Sensibilidad[j]=np.mean(recall_score(Ytest, Yest, average=None))
        Fscore[j]=np.mean(f1_score(Ytest, Yest, average=None))
    
        #Evaluamos las predicciones del modelo con los datos de test
        EVal[j] = np.mean(Yest.ravel() == Ytest.ravel())
        Porcentaje[j] =  len(modelo.support_vectors_) / len(Xtrain)
        j += 1

    
    eficiencia = np.mean(EVal)
    intervaloConfianza = np.std(EVal)
    porcentaje = np.mean(Porcentaje)
    
    return eficiencia, intervaloConfianza, np.mean(Eficiencia),np.mean(Precision), np.mean(Sensibilidad), np.mean(Fscore), porcentaje

In [ ]:
#Aplicando maquinas de Vectores
df_types2 = pd.DataFrame({
    'Kernel' : pd.Series(['linear','linear','linear','linear','linear','linear','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf']),
    'C' : pd.Series([0.001,0.01,0.1,1,10,100,0.001,0.001,0.001,0.01,0.01,0.01,0.1,0.1,0.1,1,1,1,10,10,10,100,100,100]),
    'gamma' : pd.Series([0,0,0,0,0,0,0.01,0.1,1,0.01,0.1,1,0.01,0.1,1,0.01,0.1,1,0.01,0.1,1,0.01,0.1,1])})
df_types2["% de Vectores de Soporte"] = ""
df_types2["Eficiencia en validacion"] = ""
df_types2["Intervalo de confianza"] = ""
df_types2["Eficiencia"] = ""
df_types2["Precisiòn"] = ""
df_types2["Sensibilidad"] = ""
df_types2["Fscore"] = ""

df_types2.set_index(['Kernel','C','gamma'], inplace=True)
#df_types.sort_index(inplace=True)

arrEficienciaVal = []
arrInConfianza= []
arrEficiencia=[]
arrPrecision=[]
arrSensibilidad=[]
arrFscore=[]
arrPorcentaje=[]

for h in df_types2.index:
    eficienciaVal, intervaloConfianza,Eficiencia, Precision, Sensibilidad, Fscore, porcentaje = entrenamientoMV(h[0],h[1],h[2])   
    arrEficienciaVal.append(eficienciaVal)
    arrInConfianza.append(intervaloConfianza)
    arrEficiencia.append(Eficiencia)
    arrPrecision.append(Precision)
    arrSensibilidad.append(Sensibilidad)
    arrFscore.append(Fscore)
    arrPorcentaje.append(porcentaje)
        
df_types2["Eficiencia en validacion"] = arrEficienciaVal
df_types2["Intervalo de confianza"] = arrInConfianza
df_types2["Eficiencia"] = arrEficiencia
df_types2["Precisiòn"] = arrPrecision
df_types2["Sensibilidad"] = arrSensibilidad
df_types2["Fscore"] = arrFscore
df_types2["% de Vectores de Soporte"] = arrPorcentaje

In [ ]:
qgrid_widget = qgrid.show_grid(df_types2, show_toolbar=False)
qgrid_widget
qgrid_widget.get_changed_df()

In [ ]:
def entrenamiento_sin_seleccion_caracteristicas(splits, X, Y):
   
    #Implemetamos la metodología de validación
    Errores = np.ones(splits)
    Score = np.ones(splits)
    times = np.ones(splits)
    j = 0
    kf = KFold(n_splits=splits)
    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = Y[train_index], Y[test_index]
        scaler = StandardScaler()
        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)
        #Creamos el clasificador SVM.
        clf = SVC(kernel="linear", C=1)
        #Aquí se entran y se valida el modelo sin hacer selección de características
        ######
        # Entrenamiento el modelo.
        #Para calcular el costo computacional
        tiempo_i = time.time()
        clf.fit(X_train,y_train)
        # Validación del modelo
        Errores[j] = accuracy_score(y_true=y_test, y_pred=clf.predict(X_test))
        times[j] = time.time()-tiempo_i
        j+=1

    return clf, np.mean(Errores), np.std(Errores), np.mean(times)

In [ ]:
def recursive_feature_elimination_wrapper(estimator, feature_numbers, X,Y):
    rfe = RFE(estimator=estimator, step=1,n_features_to_select=feature_numbers)
    tiempo_i = time.time()
    rfe.fit(X=X,y=Y)
    time_o = time.time()-tiempo_i
    feature_mask = rfe.support_
    #print(feature_mask)
    features_rank = rfe.ranking_
    #print(features_rank)
    estimator = rfe.estimator_
    #print(estimator)
    #print(rfe)
    
    return rfe, feature_mask, features_rank, estimator, time_o

In [ ]:
def experimentar(n_feats, n_sets, X, Y):
    df = pd.DataFrame()
    idx = 0
    for split_number in n_sets: 
    #Sin selección de características
        # se ignorar las otras salidas
        _,err,ic,t_ex = entrenamiento_sin_seleccion_caracteristicas(split_number, X,Y)  
        df.loc[idx,'CON_SEL'] = 'NO'
        df.loc[idx,'NUM_VAR'] = X.shape[1]
        df.loc[idx,'NUM_SPLITS'] = split_number
        df.loc[idx,'ERROR_VALIDACION'] = err
        df.loc[idx,'IC_STD_VALIDACION'] = ic
        df.loc[idx,'T_EJECUCION'] = t_ex
        idx+=1
    print("termina experimentos sin selección")
    #Con selección de características
    for f in n_feats:
        for split_number in n_sets:
            #Implemetamos la metodología de validación 
            Errores = np.ones(split_number)
            Score = np.ones(split_number)
            times = np.ones(split_number)
            kf = KFold(n_splits=split_number)
            j = 0
            for train_index, test_index in kf.split(X):
                
                X_train, X_test = X[train_index], X[test_index]
                y_train, y_test = Y[train_index], Y[test_index]
                scaler = StandardScaler()
                X_train = scaler.fit_transform(X_train)
                X_test = scaler.transform(X_test)
                
                svc =  SVC(kernel="linear", C=1)
                
                # se ignorar las otras salidas
                rfe, _, _, _, t = recursive_feature_elimination_wrapper(estimator=svc,feature_numbers=f, X=X_test,Y=y_test)
            
                Errores[j]=accuracy_score(y_true = y_test,  y_pred=rfe.predict(X_test))
                times[j] = t
                j+=1

            df.loc[idx,'CON_SEL'] = 'SI'
            df.loc[idx,'NUM_VAR'] = f
            df.loc[idx,'NUM_SPLITS'] = split_number
            df.loc[idx,'ERROR_VALIDACION'] = np.mean(Errores)
            df.loc[idx, 'IC_STD_VALIDACION'] = np.std(Errores)
            df.loc[idx, 'T_EJECUCION'] = np.mean(times)
            idx+=1
    return df

In [ ]:
dfr = experimentar(n_feats = [3, 5,7, 10,15,17], n_sets = [5, 10], X= X, Y=Y)

In [ ]:
dfr.sort_values(['ERROR_VALIDACION','T_EJECUCION'], ascending=[False, True])

In [ ]:
svc =  SVC(kernel="linear", C=1)
rfe, feature_mask, _, _, _ = recursive_feature_elimination_wrapper(svc,17, X,Y)
print("esta es la mascara (deberia ser solo valores True y False) \n", feature_mask)

In [ ]:
#Indice de fisher
from sklearn.feature_selection import SelectKBest, f_classif
valores = f_classif( X , Y )
print(valores)

X_new = SelectKBest(f_classif, k=1).fit(X, Y)
caracteristicas=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
atrib = X_new.get_support()
params=X_new.get_params()
atributos = [caracteristicas[i] for i in list(atrib.nonzero()[0])]
print(atrib)
atributos

In [ ]:
def MAPE(Y_est,Y):
    """Mean Absolute Percentage Error para los problemas de regresión
    Y_est: numpy array con los valores estimados
    Y: numpy array con las etiquetas verdaderas
    retorna: mape
    """
    N = np.size(Y)
    mape = np.sum(abs((Y_est.reshape(N,1) - Y.reshape(N,1))/Y.reshape(N,1)))/N
    return mape 

In [ ]:
def kernel_gaussiano(x):
    return (np.exp((-0.5)*x**2))

def ParzenWindow(x,Data,h,Datay=None):
    """"ventana de parzen
    x: vector con representando una sola muestra
    Data: vector de muestras de entrenamiento
    h: ancho de la ventana de kernel
    Datay: vector con los valores de salida (y), Si no se pasa como argumento, 
        se calcula un ventana de parzen sin multiplicar los valores de este vector.
    retorna: el valor de ventana de parzen para una muestra
    """
    h = h
    Ns = Data.shape[0]
    suma = 0
    for k in range(Ns):
        u = euclidean(x,Data[k,:])
        if Datay is None:
            suma += kernel_gaussiano(u/h)
        else:
            suma += kernel_gaussiano(u/h)*Datay[k]
    return suma

In [ ]:
def Nadaraya_Watson(X_train, Y_train, X_test, h):
    import scipy
    """ Funcion que implementa metodo de ventana de parzen para
        para clasificación
    X_train: es la matriz con las muestras de entrenamiento
    Y_train: es un vector con los valores de salida pra cada una de las muestras de entrenamiento
    X_test: es la matriz con las muestras de validación
    h (float): ancho de h de la ventana
    retorna: - las estimaciones del modelo parzen para el conjunto X_test 
              esta matriz debe tener un shape de [row/muestras de X_test]
             - las probabilidades de la vetana [row/muestras de X_test, numero de clases]  
    """
    
    Yest = np.zeros(X_test.shape[0])
    distancias = scipy.spatial.distance.cdist(X_test, X_train) / h
    #parzen=ParzenWindow(X_test,X_train,h,Y_train)
    for i in range(len(X_test)):
        pesos = kernel_gaussiano(distancias[i])
        x = np.sum(np.multiply(pesos, Y_train))
        y = np.sum(pesos)
        Yest[i] = x/y   
    
    #Debe retornar un vector que contenga las predicciones para cada una de las muestras en X_val, en el mismo orden.  
    return Yest

In [ ]:
def experimentarParzen (X, Y, hs):
    """Función que realiza los experimentos con knn usando
       una estrategia de validacion entrenamiento y pruebas
    X: matriz de numpy conjunto con muestras y caracteristicas
    Y: vector de numpy con los valores de las etiquetas
    ks: List[int/float] lista con los valores de k-vecinos a usar
    retorna: dataframe con los resultados, debe contener las siguientes columnas:
        - el ancho de ventana, 
        - el error medio de prueba
        - la desviacion estandar del error
        - número de promedio en el conjunto de prueba/validacion
    """
    # se usa la función para implementar la estrategia de validación.
    kfolds = KFold(n_splits=26)
    resultados = pd.DataFrame()
    idx = 0
    # iteramos sobre los valores de hs
    for h in hs:
        # lista para almacenar los errores y numero de muestras
        # de cada iteración
        # de la validación
        error_temp = []
        numero_muestras = []
        
        for train, test in kfolds.split(X,Y ):

            Xtrain = X[train,:]
            Ytrain = Y[train]
            Xtest = X[test,:]
            Ytest = Y[test]
            #normalizamos los datos
            scaler = StandardScaler()
            scaler.fit(Xtrain)
            Xtrain = scaler.transform(Xtrain)
            Xtest = scaler.transform(Xtest)
            Yest = Nadaraya_Watson(Xtrain,Ytrain,Xtest,h)
            errorTest = MAPE(Yest,Ytest)
            error_temp.append(errorTest)
            numero_muestras.append(len(Xtest))
            
    
        resultados.loc[idx,'ancho de ventana'] = h 
        resultados.loc[idx,'error de prueba(media)'] = np.mean(error_temp)
        resultados.loc[idx,'error de prueba(desviación estandar)'] =np.std(error_temp)
        resultados.loc[idx,'muestras en conjunto de pruebas (media)'] = np.mean(numero_muestras)
       
        idx+=1
    return (resultados)

In [ ]:
hs = [1,1.5 ,2.5, 5, 10]
experimentos_parzen = experimentarParzen(X,Y, hs)
experimentos_parzen

In [ ]:
#pca
def extract_features(tipo, n):
    """Feature Extraction Function
    Recibe 2 parámetros: 1. el tipo de método de extracción (pca o lda como string), 2. el número componentes (para pca)
    o el número de discriminantes (para lda)
    """
    if tipo == 'pca':
    
        ext = PCA(n_components=n)
    
        return ext

    elif tipo == 'lda':
        
        ext = LDA(n_components=n)
        
        return ext
    
    else:
        print ("Ingrese un método válido (pca o lda)\n")

In [ ]:
std = scale(X)

#Aquí se aplica la extracción de características por PCA
ex = extract_features('lda',14)#Complete el código llamando el método extract_features. Tenga en cuenta lo que le pide el ejercicio 3.1
#Fit de PCA
ex = ex.fit(X,Y) #Complete el código con el fit correspondiente

#Transforme las variables y genere el nuevo espacio de características de menor dimensión
X_ex = ex.transform(X) #complete el código aquí para hacer la transformación

In [ ]:
#pca mquina de  vectores
from sklearn import preprocessing
from sklearn.svm import SVC
def entrenamiento4(kernel, c, gamma):

    Folds = 4
    random.seed(19680801)
    EficienciaTrain = np.zeros(Folds)
    EficienciaVal = np.zeros(Folds)
    Eficiencia=np.zeros(Folds)
    Precision=np.zeros(Folds)
    Sensibilidad=np.zeros(Folds)
    Fscore=np.zeros(Folds)
    Porcentaje=np.zeros(Folds)
    skf = StratifiedKFold(n_splits=Folds)
    j = 0
    for train, test in skf.split(X_ex, Y):
        
        
        Xtrain = X_ex[train,:]
        Ytrain = Y[train]
        Xtest = X_ex[test,:]
        Ytest = Y[test]

        #Normalizamos los datos
        media = np.mean(Xtrain)
        desvia = np.std(Xtrain)
        #Xtrain = sc.stats.stats.zscore(Xtrain)
        #Xtest = (Xtest - np.matlib.repmat(media, Xtest.shape[0], 1))/np.matlib.repmat(desvia, Xtest.shape[0], 1)

        #Haga el llamado a la función para crear y entrenar el modelo usando los datos de entrenamiento

        
        if( kernel == 'linear'):
            modelo = SVC(kernel= kernel, C=c, decision_function_shape='ovo')#Si es Lineal
        else:
            modelo = SVC(kernel= kernel, C=c, gamma=gamma, decision_function_shape='ovo') #Si es rbf
      
    
    
        modelo.fit(Xtrain,Ytrain)
        
        Ytrain_pred = modelo.predict(Xtrain)        #Validación con las muestras de entrenamiento
        Yest = modelo.predict(Xtest)        #Validación con las muestras de test  
        
        Eficiencia[j] = accuracy_score(Ytest, Yest)
        Precision[j] =np.mean(precision_score(Ytest, Yest, average=None))
        Sensibilidad[j]=np.mean(recall_score(Ytest, Yest, average=None))
        Fscore[j]=np.mean(f1_score(Ytest, Yest, average=None))
    
        #Evaluamos las predicciones del modelo con los datos de test
        EficienciaVal[j] = np.mean(Yest.ravel() == Ytest.ravel())
        Porcentaje[j] =  len(modelo.support_vectors_) / len(Xtrain)
        j += 1

    
    eficiencia = np.mean(EficienciaVal)
    intervaloConfianza = np.std(EficienciaVal)
    porcentaje = np.mean(Porcentaje)
    
    return eficiencia, intervaloConfianza, np.mean(Eficiencia),np.mean(Precision), np.mean(Sensibilidad), np.mean(Fscore), porcentaje

In [ ]:
df_types2 = pd.DataFrame({
    'Kernel' : pd.Series(['linear','rbf']),
    'C' : pd.Series([1,100]),
    'gamma' : pd.Series([0,0.1])})
df_types2["% de Vectores de Soporte"] = ""
df_types2["Eficiencia en validacion"] = ""
df_types2["Intervalo de confianza"] = ""
df_types2["Eficiencia"] = ""
df_types2["Precisiòn"] = ""
df_types2["Sensibilidad"] = ""
df_types2["Fscore"] = ""

df_types2.set_index(['Kernel','C','gamma'], inplace=True)
#df_types.sort_index(inplace=True)

arrEficienciaVal = []
arrInConfianza= []
arrEficiencia=[]
arrPrecision=[]
arrSensibilidad=[]
arrFscore=[]
arrPorcentaje=[]

for h in df_types2.index:
    eficienciaVal, intervaloConfianza,Eficiencia, Precision, Sensibilidad, Fscore, porcentaje = entrenamiento4(h[0],h[1],h[2])   
    arrEficienciaVal.append(eficienciaVal)
    arrInConfianza.append(intervaloConfianza)
    arrEficiencia.append(Eficiencia)
    arrPrecision.append(Precision)
    arrSensibilidad.append(Sensibilidad)
    arrFscore.append(Fscore)
    arrPorcentaje.append(porcentaje)
        
df_types2["Eficiencia en validacion"] = arrEficienciaVal
df_types2["Intervalo de confianza"] = arrInConfianza
df_types2["Eficiencia"] = arrEficiencia
df_types2["Precisiòn"] = arrPrecision
df_types2["Sensibilidad"] = arrSensibilidad
df_types2["Fscore"] = arrFscore
df_types2["% de Vectores de Soporte"] = arrPorcentaje

In [ ]:
qgrid_widget = qgrid.show_grid(df_types2, show_toolbar=False)
qgrid_widget
qgrid_widget.get_changed_df()